/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileVisibilitySettingsRouteImport } from './routes/_authenticated/profile/visibility-settings'
import { Route as AuthenticatedProfileSoftwareProjectsRouteImport } from './routes/_authenticated/profile/software-projects'
import { Route as AuthenticatedProfileSkillsRouteImport } from './routes/_authenticated/profile/skills'
import { Route as AuthenticatedProfileRegisterRouteImport } from './routes/_authenticated/profile/register'
import { Route as AuthenticatedProfileLinksRouteImport } from './routes/_authenticated/profile/links'
import { Route as AuthenticatedProfileLaboralExperienceRouteImport } from './routes/_authenticated/profile/laboral-experience'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile/edit'
import { Route as AuthenticatedProfileAcademicFormationRouteImport } from './routes/_authenticated/profile/academic-formation'
import { Route as AuthenticatedProfileAcademicExperienceRouteImport } from './routes/_authenticated/profile/academic-experience'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileVisibilitySettingsRoute =
  AuthenticatedProfileVisibilitySettingsRouteImport.update({
    id: '/profile/visibility-settings',
    path: '/profile/visibility-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileSoftwareProjectsRoute =
  AuthenticatedProfileSoftwareProjectsRouteImport.update({
    id: '/profile/software-projects',
    path: '/profile/software-projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileSkillsRoute =
  AuthenticatedProfileSkillsRouteImport.update({
    id: '/profile/skills',
    path: '/profile/skills',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRegisterRoute =
  AuthenticatedProfileRegisterRouteImport.update({
    id: '/profile/register',
    path: '/profile/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileLinksRoute =
  AuthenticatedProfileLinksRouteImport.update({
    id: '/profile/links',
    path: '/profile/links',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileLaboralExperienceRoute =
  AuthenticatedProfileLaboralExperienceRouteImport.update({
    id: '/profile/laboral-experience',
    path: '/profile/laboral-experience',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileAcademicFormationRoute =
  AuthenticatedProfileAcademicFormationRouteImport.update({
    id: '/profile/academic-formation',
    path: '/profile/academic-formation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileAcademicExperienceRoute =
  AuthenticatedProfileAcademicExperienceRouteImport.update({
    id: '/profile/academic-experience',
    path: '/profile/academic-experience',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/academic-experience': typeof AuthenticatedProfileAcademicExperienceRoute
  '/profile/academic-formation': typeof AuthenticatedProfileAcademicFormationRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/laboral-experience': typeof AuthenticatedProfileLaboralExperienceRoute
  '/profile/links': typeof AuthenticatedProfileLinksRoute
  '/profile/register': typeof AuthenticatedProfileRegisterRoute
  '/profile/skills': typeof AuthenticatedProfileSkillsRoute
  '/profile/software-projects': typeof AuthenticatedProfileSoftwareProjectsRoute
  '/profile/visibility-settings': typeof AuthenticatedProfileVisibilitySettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/academic-experience': typeof AuthenticatedProfileAcademicExperienceRoute
  '/profile/academic-formation': typeof AuthenticatedProfileAcademicFormationRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/laboral-experience': typeof AuthenticatedProfileLaboralExperienceRoute
  '/profile/links': typeof AuthenticatedProfileLinksRoute
  '/profile/register': typeof AuthenticatedProfileRegisterRoute
  '/profile/skills': typeof AuthenticatedProfileSkillsRoute
  '/profile/software-projects': typeof AuthenticatedProfileSoftwareProjectsRoute
  '/profile/visibility-settings': typeof AuthenticatedProfileVisibilitySettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/_authenticated/profile/academic-experience': typeof AuthenticatedProfileAcademicExperienceRoute
  '/_authenticated/profile/academic-formation': typeof AuthenticatedProfileAcademicFormationRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/laboral-experience': typeof AuthenticatedProfileLaboralExperienceRoute
  '/_authenticated/profile/links': typeof AuthenticatedProfileLinksRoute
  '/_authenticated/profile/register': typeof AuthenticatedProfileRegisterRoute
  '/_authenticated/profile/skills': typeof AuthenticatedProfileSkillsRoute
  '/_authenticated/profile/software-projects': typeof AuthenticatedProfileSoftwareProjectsRoute
  '/_authenticated/profile/visibility-settings': typeof AuthenticatedProfileVisibilitySettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/profile/$username'
    | '/profile/academic-experience'
    | '/profile/academic-formation'
    | '/profile/edit'
    | '/profile/laboral-experience'
    | '/profile/links'
    | '/profile/register'
    | '/profile/skills'
    | '/profile/software-projects'
    | '/profile/visibility-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/profile/$username'
    | '/profile/academic-experience'
    | '/profile/academic-formation'
    | '/profile/edit'
    | '/profile/laboral-experience'
    | '/profile/links'
    | '/profile/register'
    | '/profile/skills'
    | '/profile/software-projects'
    | '/profile/visibility-settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/register'
    | '/_public/reset-password'
    | '/_public/verify-email'
    | '/profile/$username'
    | '/_authenticated/profile/academic-experience'
    | '/_authenticated/profile/academic-formation'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/laboral-experience'
    | '/_authenticated/profile/links'
    | '/_authenticated/profile/register'
    | '/_authenticated/profile/skills'
    | '/_authenticated/profile/software-projects'
    | '/_authenticated/profile/visibility-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/visibility-settings': {
      id: '/_authenticated/profile/visibility-settings'
      path: '/profile/visibility-settings'
      fullPath: '/profile/visibility-settings'
      preLoaderRoute: typeof AuthenticatedProfileVisibilitySettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/software-projects': {
      id: '/_authenticated/profile/software-projects'
      path: '/profile/software-projects'
      fullPath: '/profile/software-projects'
      preLoaderRoute: typeof AuthenticatedProfileSoftwareProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/skills': {
      id: '/_authenticated/profile/skills'
      path: '/profile/skills'
      fullPath: '/profile/skills'
      preLoaderRoute: typeof AuthenticatedProfileSkillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/register': {
      id: '/_authenticated/profile/register'
      path: '/profile/register'
      fullPath: '/profile/register'
      preLoaderRoute: typeof AuthenticatedProfileRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/links': {
      id: '/_authenticated/profile/links'
      path: '/profile/links'
      fullPath: '/profile/links'
      preLoaderRoute: typeof AuthenticatedProfileLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/laboral-experience': {
      id: '/_authenticated/profile/laboral-experience'
      path: '/profile/laboral-experience'
      fullPath: '/profile/laboral-experience'
      preLoaderRoute: typeof AuthenticatedProfileLaboralExperienceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/academic-formation': {
      id: '/_authenticated/profile/academic-formation'
      path: '/profile/academic-formation'
      fullPath: '/profile/academic-formation'
      preLoaderRoute: typeof AuthenticatedProfileAcademicFormationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/academic-experience': {
      id: '/_authenticated/profile/academic-experience'
      path: '/profile/academic-experience'
      fullPath: '/profile/academic-experience'
      preLoaderRoute: typeof AuthenticatedProfileAcademicExperienceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileAcademicExperienceRoute: typeof AuthenticatedProfileAcademicExperienceRoute
  AuthenticatedProfileAcademicFormationRoute: typeof AuthenticatedProfileAcademicFormationRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileLaboralExperienceRoute: typeof AuthenticatedProfileLaboralExperienceRoute
  AuthenticatedProfileLinksRoute: typeof AuthenticatedProfileLinksRoute
  AuthenticatedProfileRegisterRoute: typeof AuthenticatedProfileRegisterRoute
  AuthenticatedProfileSkillsRoute: typeof AuthenticatedProfileSkillsRoute
  AuthenticatedProfileSoftwareProjectsRoute: typeof AuthenticatedProfileSoftwareProjectsRoute
  AuthenticatedProfileVisibilitySettingsRoute: typeof AuthenticatedProfileVisibilitySettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileAcademicExperienceRoute:
    AuthenticatedProfileAcademicExperienceRoute,
  AuthenticatedProfileAcademicFormationRoute:
    AuthenticatedProfileAcademicFormationRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileLaboralExperienceRoute:
    AuthenticatedProfileLaboralExperienceRoute,
  AuthenticatedProfileLinksRoute: AuthenticatedProfileLinksRoute,
  AuthenticatedProfileRegisterRoute: AuthenticatedProfileRegisterRoute,
  AuthenticatedProfileSkillsRoute: AuthenticatedProfileSkillsRoute,
  AuthenticatedProfileSoftwareProjectsRoute:
    AuthenticatedProfileSoftwareProjectsRoute,
  AuthenticatedProfileVisibilitySettingsRoute:
    AuthenticatedProfileVisibilitySettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
